<a href="https://colab.research.google.com/github/NEFAxRAJ/Machine-Learning-Practices/blob/main/Spam_Data_Cleaning_and_vectorization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/sms_spam.csv')
dataset= pd.DataFrame(df)
data= pd.DataFrame(df)
data.head(5)

   type                                               text
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
data.isnull().sum()

type    0
text    0
dtype: int64

In [ ]:
# Label ham= 0 and spam= 1 using labelencoder
from sklearn.preprocessing import LabelEncoder

data['type']= LabelEncoder().fit_transform(data['type'])
data.head(2)

   type                                               text
0     0  Go until jurong point, crazy.. Available only ...
1     0                      Ok lar... Joking wif u oni...

In [ ]:
# Label ham= 10 and spam= 11 manually

type_label={
    'ham': 10,
    'spam' : 11
}

dataset['type']= dataset['type'].map(type_label)
dataset.head(2)

   type                                               text
0    10  Go until jurong point, crazy.. Available only ...
1    10                      Ok lar... Joking wif u oni...

In [ ]:
# Checking and removing duplicate values
data.duplicated().sum()

np.int64(414)

In [ ]:
data=data.drop_duplicates(keep='first')
data.duplicated().sum()

np.int64(0)

In [ ]:
## Data Pre-processing
    #1. Lower Case
    #2. Tokenization
    #3. Removing special characters
    #4. Removing stop words and punctuation
    #5. Stemming

In [ ]:
import nltk
nltk.download('punkt_tab')
nltk.download('stopwords')
from nltk.corpus import stopwords
import string
from nltk.stem.porter import PorterStemmer as ps

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [ ]:
def text_preprocess(text):

  text=text.lower()
  text= nltk.word_tokenize(text)
  y=[]
  for i in text:
    if(i not in stopwords.words('english') and i not in string.punctuation and i.isalnum()):
      y.append(ps().stem(i))
  return " ".join(y)

In [ ]:
text="Hi how are you not dancing today?"
txt=text_preprocess(text)
print(txt)

hi danc today

In [ ]:
#Creating a new column of transformed text
data['transformed_text']=data['text'].apply(text_preprocess)
data.head(3)

,type,text,transformed_text
0,0,"Go until jurong point, crazy.. Available only ...",go jurong point crazi avail bugi n great world...
1,0,Ok lar... Joking wif u oni...,ok lar joke wif u oni
2,1,Free entry in 2 a wkly comp to win FA Cup fina...,free entri 2 wkli comp win fa cup final tkt 21...

In [ ]:
#Vectorizing the data
from sklearn.feature_extraction.text import TfidfVectorizer
x=TfidfVectorizer().fit_transform(data['transformed_text']).toarray()
y=data['type'].values

In [ ]:
#Splitting the dataset into Train And Test Dataset
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.8,random_state=2)

In [ ]:
x_train.shape

(1032, 6784)

In [ ]:
y_train.shape

(1032,)